-- CreateTable
CREATE TABLE `cotacao` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `COIN_TYPE` VARCHAR(10) NOT NULL,
    `VALUE` FLOAT NOT NULL,
    `DATE_REGISTER` DATETIME NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
